feat: add security and autentification with oAuth2 google-protected e…
zvic81/GymSubscribe pull request #3
Opened 2024-04-17 14:40 UTC by zvic81

…ndpoints subscribes and clients

fix: readmi.md, dockerfile, add secret.env (in gitignore)

2024-04-17 15:07 UTC, css-ilgol requested changes

2024-04-17 15:07 UTC, css-ilgol commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_secret}
а чего не GOOGLE_CLIENT_SECRET?

2024-04-17 15:07 UTC, css-ilgol commented on src/main/java/com/example/gymsubscribe/controller/SubscribeController.java
>      @PostMapping("/add_client")
add_client плохое название для эндпоинта.
post-запрос client сам по себе подразумевает, что ты будешь добавлять.
get/{id} получать и т.д.
вот почитай: https://habr.com/ru/articles/483202/

2024-04-17 15:07 UTC, css-ilgol commented on src/main/java/com/example/gymsubscribe/controller/SubscribeController.java
>      @PostMapping("/add_client")
аналогично для add_subscribe и других.
Кстати подписка - subscription а не subscribe

2024-04-17 16:20 UTC, zvic81 commented on src/main/resources/application.properties
> +spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_secret}
fixed

2024-04-17 16:26 UTC, zvic81 commented on src/main/java/com/example/gymsubscribe/controller/SubscribeController.java
>      @PostMapping("/add_client")
fixed

2024-04-24 19:10 UTC, css-ilgol commented on src/main/java/com/example/gymsubscribe/controller/SubscribeController.java
> +    public String index(Model model){
пробел между ) {

2024-04-24 19:10 UTC, css-ilgol commented on src/main/java/com/example/gymsubscribe/service/impl/ClientServiceImpl.java
> +    }
Client findById(Long id);

2024-04-24 19:13 UTC, css-ilgol approved these changes

2024-04-24 19:28 UTC, merged